### ISSUE TITLE
Release stable versions

### ISSUE THREAD

**Issue by duboism** [Rfam/rfam-taxonomy#2]
Hello,

I was thinking that you could create proper tags and release. This way one can easily download the data associated with a release of `Rfam`.

Also it might be worth to not store the data inside git (only the code) but to add them in the archive of the stable release.

**Comment by AntonPetrov** [comment]
Great idea! I've set up tags and releases and will make sure a new one is created for each future Rfam release:
https://github.com/Rfam/rfam-taxonomy/releases

Not storing the data in git is also a good idea but would require some work so it would have to wait.

@duboism Would you mind sharing how you use the data in this repo? We are planning some improvements to the algorithm and it would be very useful for us to know how the data is used and what we can do better.

**Comment by duboism** [comment]
Hello,

thanks for your reactivity. Don't hesitate if you need help (though I'm far from being an expert). By the way, we noticed that [prokka ](https://github.com/tseemann/prokka/) uses a similar approach (see scripts in `db/cm/__build/`).

Right now we don't use the code/data but we are thinking about it. Basically we want a list of families found in Bacteria to filter `infernal` results (i.e. keep only families found in Bacteria). Therefore, we could use the `bacteria.csv` file to do that.

**Comment by AntonPetrov** [comment]
Thank you for the information! This is very useful - I was not aware of the prokka files.

A quick look at the [prokka bacteria list](https://github.com/tseemann/prokka/blob/master/db/cm/__build/Rfam_bacteria_14.1.txt) shows several false positives, such as `Metazoan signal recognition particle RNA`, `Small nucleolar RNA U3`, `Small nucleolar RNA SNORD36` to name a few. This happens because [according to the SQL query that is used to create this list](https://github.com/tseemann/prokka/blob/master/db/cm/__build/bacteria.sql), a single contaminated sequence is enough for the entire family to be classified as found in a certain domain. I will raise an issue in the prokka repo to discuss.

I would suggest using this repo because it analyses the taxonomic distribution in both the seed and the full region hits, and enforces that at least 90% of the hits must be from the same domain in order for a family to be classified as belonging to, say, Bacteria.

Let me know if you have any questions or run into any issues with `bacteria.csv`. Thank you!

**Comment by blakesweeney** [comment]
Hi, I'm going to close this issue as we will be moving the rfam-taxonomy files into part of the release process and place them on our FTP.
